# Generated by Django 2.0.4 on 2018-04-17 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='name', max_length=100)),
                ('inn', models.CharField(blank=True, default='ИНН', max_length=15)),
                ('rail_code', models.CharField(blank=True, default='9999', max_length=4)),
            ],
            options={
                'verbose_name': 'Person',
                'verbose_name_plural': 'Persons',
                'ordering': ('name',),
            },
        ),
    ]
