# Generated by Django 2.0.6 on 2018-07-17 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_container', models.NullBooleanField()),
                ('container_tare', models.FloatField(null=True)),
                ('description', models.TextField(blank=True)),
                ('tnved_code', models.CharField(blank=True, max_length=50)),
                ('tved_description', models.TextField(blank=True)),
                ('gng_code', models.CharField(blank=True, max_length=50)),
                ('gng_description', models.TextField(blank=True)),
                ('etsng_code', models.CharField(blank=True, max_length=50)),
                ('package_quantity', models.IntegerField(null=True)),
                ('unit_quantity', models.FloatField(null=True)),
                ('nett_weight', models.FloatField(null=True)),
                ('gross_weight', models.FloatField(null=True)),
            ],
            options={
                'verbose_name': 'Cargo',
                'verbose_name_plural': 'Cargos',
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_abbr', models.CharField(default='EUR', max_length=50)),
                ('currency_code', models.CharField(default='978', max_length=50)),
            ],
            options={
                'verbose_name': 'Currency',
                'verbose_name_plural': 'Currencies',
            },
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='XXX-XXXX', max_length=10)),
                ('goods', models.ManyToManyField(to='rest.Cargo')),
            ],
            options={
                'verbose_name': 'Factura',
                'verbose_name_plural': 'Facturas',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(blank=True, default='RLS', max_length=10)),
                ('created', models.DateField(auto_now_add=True)),
                ('will_arrive', models.DateField()),
                ('is_closed', models.BooleanField(default=False)),
                ('short_description', models.CharField(blank=True, default='name', max_length=100)),
                ('description', models.TextField(blank=True)),
                ('inbound_bill', models.CharField(blank=True, max_length=30)),
                ('transit_or_export', models.CharField(blank=True, max_length=10)),
                ('total_inbound_places', models.IntegerField(null=True)),
                ('total_inbound_gross', models.FloatField(null=True)),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
            },
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_name_rus', models.CharField(blank=True, max_length=30)),
                ('package_name_eng', models.CharField(blank=True, max_length=30)),
                ('package_code', models.CharField(blank=True, max_length=3)),
            ],
            options={
                'verbose_name': 'Package',
                'verbose_name_plural': 'Packages',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='name', max_length=100)),
                ('inn', models.CharField(blank=True, default='ИНН', max_length=15)),
                ('rail_code', models.CharField(blank=True, default='9999', max_length=4)),
            ],
            options={
                'verbose_name': 'Person',
                'verbose_name_plural': 'Persons',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_name', models.CharField(blank=True, max_length=50)),
                ('place_code', models.CharField(default='000000', max_length=6)),
                ('is_border', models.NullBooleanField(default=False)),
                ('road_name', models.CharField(blank=True, max_length=100)),
                ('road_name_abbr', models.CharField(blank=True, max_length=4)),
                ('road_code', models.CharField(blank=True, max_length=4)),
                ('road_operator_name', models.CharField(blank=True, max_length=20)),
            ],
            options={
                'verbose_name': 'Place',
                'verbose_name_plural': 'Places',
            },
        ),
        migrations.CreateModel(
            name='Railbill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='00000000', max_length=10)),
                ('gr_23', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Railbill',
                'verbose_name_plural': 'Railbills',
            },
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=6)),
                ('incoterms_abbr', models.CharField(default='CIP', max_length=3)),
                ('incoterms_place', models.CharField(default='RIGA', max_length=50)),
                ('belongs_to_order', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='rest.Order')),
                ('buyer', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='buyer', to='rest.Person')),
                ('currency', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='rest.Currency')),
                ('facturas', models.ManyToManyField(default=1, to='rest.Factura')),
                ('outbound_cargo', models.ManyToManyField(to='rest.Cargo')),
                ('railbill', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='rest.Railbill')),
                ('seller', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='seller', to='rest.Person')),
            ],
            options={
                'verbose_name': 'Shipment',
                'verbose_name_plural': 'Shipments',
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_name_full', models.CharField(blank=True, max_length=30)),
                ('unit_name_short', models.CharField(blank=True, max_length=30)),
                ('unit_code', models.CharField(blank=True, max_length=5)),
            ],
            options={
                'verbose_name': 'Unit',
                'verbose_name_plural': 'Units',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='consignee',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='consignee', to='rest.Person'),
        ),
        migrations.AddField(
            model_name='order',
            name='consignor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='consignor', to='rest.Person'),
        ),
        migrations.AddField(
            model_name='order',
            name='destination_place',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='destination_place', to='rest.Place'),
        ),
        migrations.AddField(
            model_name='order',
            name='dispatch_place',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='dispatch_place', to='rest.Place'),
        ),
        migrations.AddField(
            model_name='order',
            name='inbound_cargo',
            field=models.ManyToManyField(blank=True, to='rest.Cargo'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipments',
            field=models.ManyToManyField(blank=True, related_name='shipments', to='rest.Shipment'),
        ),
        migrations.AddField(
            model_name='cargo',
            name='package',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='rest.Package'),
        ),
        migrations.AddField(
            model_name='cargo',
            name='unit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='rest.Unit'),
        ),
    ]
