# Generated by Django 2.0.6 on 2018-08-25 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True)),
                ('created', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
            },
        ),
        migrations.AlterField(
            model_name='order',
            name='short_description',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='buyer',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='buyer', to='rest.Person'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='currency',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='rest.Currency'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='facturas',
            field=models.ManyToManyField(blank=True, default=1, to='rest.Factura'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='outbound_cargo',
            field=models.ManyToManyField(blank=True, to='rest.Cargo'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='railbill',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='rest.Railbill'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='seller',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='seller', to='rest.Person'),
        ),
        migrations.AddField(
            model_name='order',
            name='comments',
            field=models.ManyToManyField(blank=True, related_name='comments', to='rest.Comment'),
        ),
    ]
