# Generated by Django 2.0.4 on 2018-04-18 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(blank=True, default='RLS', max_length=10)),
                ('short_description', models.CharField(blank=True, default='name', max_length=100)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
            },
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('place_type', models.CharField(blank=True, choices=[('port', 'SEA PORT'), ('rwst', 'RAIL STATION')], max_length=50)),
                ('is_border', models.BooleanField()),
            ],
            options={
                'verbose_name': 'Place',
                'verbose_name_plural': 'Places',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='destination_place',
            field=models.ManyToManyField(related_name='destination_place', to='rest.Place'),
        ),
        migrations.AddField(
            model_name='order',
            name='dispatch_place',
            field=models.ManyToManyField(related_name='dispatch_place', to='rest.Place'),
        ),
    ]
