# Generated by Django 2.0.6 on 2018-08-25 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0002_auto_20180825_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='order',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='rest.Order'),
        ),
    ]
