# Generated by Django 2.0.4 on 2018-04-19 18:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0003_auto_20180419_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='is_closed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='will_arrive',
            field=models.DateField(default=datetime.date(2018, 4, 19)),
        ),
    ]
