# Generated by Django 2.0.6 on 2018-08-28 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0003_comment_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20)),
                ('containers_type', models.CharField(blank=True, max_length=6)),
                ('payload', models.CharField(blank=True, max_length=2)),
                ('tare', models.IntegerField(blank=True)),
            ],
            options={
                'verbose_name': 'Container',
                'verbose_name_plural': 'Containers',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_rus', models.CharField(blank=True, max_length=100)),
                ('name_eng', models.CharField(blank=True, max_length=100)),
                ('name_lat', models.CharField(blank=True, max_length=100)),
                ('code', models.CharField(blank=True, max_length=10)),
            ],
            options={
                'verbose_name': 'Country',
                'verbose_name_plural': 'Countrys',
            },
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='facturas',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='incoterms_abbr',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='incoterms_place',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='outbound_cargo',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='railbill',
        ),
        migrations.AddField(
            model_name='person',
            name='city',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='person',
            name='okpo',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='person',
            name='phone',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='person',
            name='postal_code',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='person',
            name='region',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='person',
            name='street_house',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='shipment',
            name='cargo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cargo', to='rest.Cargo'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='cargo_is_general',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='shipment',
            name='contract',
            field=models.CharField(default='ПО ИНВОЙСУ', max_length=50),
        ),
        migrations.AddField(
            model_name='shipment',
            name='order',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='rest.Order'),
        ),
        migrations.AlterField(
            model_name='order',
            name='comments',
            field=models.ManyToManyField(blank=True, null=True, related_name='comments', to='rest.Comment'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipments',
            field=models.ManyToManyField(blank=True, null=True, related_name='shipments', to='rest.Shipment'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='buyer',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='buyer', to='rest.Person'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='seller',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seller', to='rest.Person'),
        ),
        migrations.AddField(
            model_name='person',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='country', to='rest.Country'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='container',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='container', to='rest.Container'),
        ),
    ]
