# Generated by Django 2.0.4 on 2018-04-19 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0004_auto_20180419_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='shipments',
            field=models.ManyToManyField(blank=True, related_name='shipments', to='rest.Shipment'),
        ),
        migrations.AlterField(
            model_name='order',
            name='will_arrive',
            field=models.DateField(auto_now=True),
        ),
    ]
