# Generated by Django 2.0.4 on 2018-04-20 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0006_shipment_from_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller', models.CharField(default='seller', max_length=50)),
                ('name', models.CharField(default='XXX-XXXX', max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RailBill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller', models.CharField(default='seller', max_length=50)),
                ('name', models.CharField(default='rwb', max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
