# Generated by Django 2.0.6 on 2018-09-04 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0006_auto_20180901_2015'),
    ]

    operations = [
        migrations.RenameField(
            model_name='unit',
            old_name='unit_code',
            new_name='code',
        ),
        migrations.RenameField(
            model_name='unit',
            old_name='unit_name_full',
            new_name='name_full',
        ),
        migrations.RenameField(
            model_name='unit',
            old_name='unit_name_short',
            new_name='name_full_eng',
        ),
        migrations.AddField(
            model_name='unit',
            name='name_short',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='unit',
            name='name_short_eng',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
