# Generated by Django 2.0.6 on 2018-09-05 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0007_auto_20180904_1756'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='print_name',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
