# Generated by Django 2.0.4 on 2018-04-20 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0007_factura_railbill'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True)),
                ('tnved_code', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'verbose_name': 'Cargo',
                'verbose_name_plural': 'Cargos',
            },
        ),
        migrations.AlterModelOptions(
            name='factura',
            options={'verbose_name': 'Factura', 'verbose_name_plural': 'Facturas'},
        ),
        migrations.AlterModelOptions(
            name='railbill',
            options={'verbose_name': 'Railbill', 'verbose_name_plural': 'Railbills'},
        ),
        migrations.RemoveField(
            model_name='factura',
            name='seller',
        ),
        migrations.RemoveField(
            model_name='railbill',
            name='seller',
        ),
        migrations.AddField(
            model_name='railbill',
            name='shipment',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='rest.Shipment'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shipment',
            name='consignee',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='consignee', to='rest.Person'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shipment',
            name='consignor',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='consignor', to='rest.Person'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shipment',
            name='facturas',
            field=models.ManyToManyField(to='rest.Factura'),
        ),
        migrations.AlterField(
            model_name='railbill',
            name='name',
            field=models.CharField(default='00000000', max_length=10),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='from_order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='rest.Order'),
        ),
        migrations.AddField(
            model_name='factura',
            name='goods',
            field=models.ManyToManyField(to='rest.Cargo'),
        ),
    ]
