# Generated by Django 2.0.6 on 2018-09-07 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0008_package_print_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factura',
            name='goods',
        ),
        migrations.AddField(
            model_name='factura',
            name='buyer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='factura_buyer', to='rest.Person'),
        ),
        migrations.AddField(
            model_name='factura',
            name='cargo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='factura_cargo', to='rest.Cargo'),
        ),
        migrations.AddField(
            model_name='factura',
            name='consignee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='factura_consignee', to='rest.Person'),
        ),
        migrations.AddField(
            model_name='factura',
            name='consignor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='factura_consignor', to='rest.Person'),
        ),
        migrations.AddField(
            model_name='factura',
            name='contract_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='factura',
            name='contract_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='factura',
            name='currency',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='factura',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='factura',
            name='delivery_terms_place',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='factura',
            name='delivery_terms_str_code',
            field=models.CharField(default='CIP', max_length=3),
        ),
        migrations.AddField(
            model_name='factura',
            name='doc_name',
            field=models.CharField(default='СЧЕТ-ФАКТУРА', max_length=50),
        ),
        migrations.AddField(
            model_name='factura',
            name='footer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='factura',
            name='gross',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='factura',
            name='nett',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='factura',
            name='pcs',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='factura',
            name='places',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='factura',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='factura',
            name='seller',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='factura_seller', to='rest.Person'),
        ),
        migrations.AddField(
            model_name='factura',
            name='total_amount',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
