# Generated by Django 2.0.4 on 2018-04-20 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0008_auto_20180420_2342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='facturas',
            field=models.ManyToManyField(blank=True, to='rest.Factura'),
        ),
    ]
