# Generated by Django 2.0.4 on 2018-04-20 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0009_auto_20180421_0001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='consignee',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='consignee', to='rest.Person'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='consignor',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='consignor', to='rest.Person'),
        ),
    ]
