# Generated by Django 2.0.6 on 2018-09-07 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0009_auto_20180907_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='facturas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shipments_facturas', to='rest.Factura'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='rw_bill',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='rest.Railbill'),
        ),
    ]
