# Generated by Django 2.0.4 on 2018-04-20 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0010_auto_20180421_0008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='from_order',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='rest.Order'),
        ),
    ]
