# Generated by Django 2.0.6 on 2018-09-14 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0011_auto_20180912_0901'),
    ]

    operations = [
        migrations.CreateModel(
            name='InboundDoc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(default='Bill Of Lading', max_length=20)),
                ('number', models.CharField(blank=True, max_length=20)),
                ('places', models.IntegerField(default=0)),
                ('gross', models.FloatField(default=0.0)),
            ],
            options={
                'verbose_name': 'InboundDoc',
                'verbose_name_plural': 'InboundDocs',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='inbound_docs',
            field=models.ManyToManyField(blank=True, to='rest.InboundDoc'),
        ),
    ]
