# Generated by Django 2.0.4 on 2018-04-20 21:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0011_auto_20180421_0011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='consignee',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='consignee', to='rest.Person'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='consignor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='consignor', to='rest.Person'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='facturas',
            field=models.ManyToManyField(blank=True, null=True, to='rest.Factura'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='from_order',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='rest.Order'),
        ),
    ]
