# Generated by Django 2.0.6 on 2018-09-17 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0012_auto_20180914_2035'),
    ]

    operations = [
        migrations.AddField(
            model_name='container',
            name='owner',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='container',
            name='containers_type',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='container',
            name='name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='container',
            name='payload',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='container',
            name='tare',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
