# Generated by Django 2.0.4 on 2018-04-21 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0013_auto_20180421_0031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='destination_place',
        ),
        migrations.AddField(
            model_name='order',
            name='destination_place',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='destination_place', to='rest.Place'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='order',
            name='dispatch_place',
        ),
        migrations.AddField(
            model_name='order',
            name='dispatch_place',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='dispatch_place', to='rest.Place'),
            preserve_default=False,
        ),
    ]
