# Generated by Django 2.0.4 on 2018-06-17 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0014_auto_20180421_1844'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='railbill',
            name='shipment',
        ),
        migrations.DeleteModel(
            name='RailBill',
        ),
    ]
