# Generated by Django 2.0.4 on 2018-06-17 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0015_auto_20180617_2001'),
    ]

    operations = [
        migrations.CreateModel(
            name='Railbill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='00000000', max_length=10)),
                ('shipment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='rest.Shipment')),
            ],
            options={
                'verbose_name': 'Railbill',
                'verbose_name_plural': 'Railbills',
            },
        ),
    ]
