# Generated by Django 2.0.6 on 2018-09-17 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0016_cargo_invoice_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=50)),
                ('date', models.DateField(auto_now=True)),
                ('incoterms_place', models.CharField(blank=True, max_length=50)),
                ('incoterms_code', models.CharField(default='CIP', max_length=3)),
                ('units_qty', models.FloatField(default=0.0)),
                ('packages_qty', models.IntegerField(default=0)),
                ('nett_kgs', models.FloatField(default=0.0)),
                ('gross_kgs', models.FloatField(default=0.0)),
                ('buyer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inv_buyer', to='rest.Person')),
                ('consignee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inv_consignee', to='rest.Person')),
                ('package', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inv_package', to='rest.Package')),
                ('seller', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inv_seller', to='rest.Person')),
                ('unit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inv_unit', to='rest.Unit')),
            ],
            options={
                'verbose_name': 'Invoice',
                'verbose_name_plural': 'Invoices',
            },
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='cargo',
        ),
        migrations.AlterField(
            model_name='shipment',
            name='buyer',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='buyer', to='rest.Person'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='seller',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='seller', to='rest.Person'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='invoices',
            field=models.ManyToManyField(related_name='shipment_invoices', to='rest.Invoice'),
        ),
    ]
