# Generated by Django 2.0.6 on 2018-06-27 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0016_railbill'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='name',
            new_name='place_name',
        ),
        migrations.AddField(
            model_name='place',
            name='place_code',
            field=models.CharField(default='000000', max_length=6),
        ),
        migrations.AddField(
            model_name='place',
            name='road_code',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name='place',
            name='road_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='place',
            name='road_name_abbr',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name='place',
            name='road_operator_name',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
