# Generated by Django 2.0.6 on 2018-06-29 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0017_auto_20180627_1714'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='place_type',
        ),
        migrations.AlterField(
            model_name='place',
            name='is_border',
            field=models.BooleanField(default=False),
        ),
    ]
