# Generated by Django 2.0.6 on 2018-09-19 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0017_auto_20180917_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='buyer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='factura_buyer', to='rest.Person'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='cargo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='factura_cargo', to='rest.Cargo'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='consignee',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='factura_consignee', to='rest.Person'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='consignor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='factura_consignor', to='rest.Person'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='seller',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='factura_seller', to='rest.Person'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='buyer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='inv_buyer', to='rest.Person'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='consignee',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='inv_consignee', to='rest.Person'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='package',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='inv_package', to='rest.Package'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='seller',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='inv_seller', to='rest.Person'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='unit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='inv_unit', to='rest.Unit'),
        ),
        migrations.AlterField(
            model_name='order',
            name='consignee',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='consignee', to='rest.Person'),
        ),
        migrations.AlterField(
            model_name='order',
            name='consignor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='consignor', to='rest.Person'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='buyer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='buyer', to='rest.Person'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='container',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='container', to='rest.Container'),
        ),
        # migrations.AlterField(
        #     model_name='shipment',
        #     name='rw_bill',
        #     field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='rest.Railbill'),
        # ),
        migrations.AlterField(
            model_name='shipment',
            name='seller',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='seller', to='rest.Person'),
        ),
    ]
