# Generated by Django 2.0.6 on 2018-09-20 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0019_auto_20180919_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='currency',
            field=models.CharField(blank=True, max_length=3),
        ),
    ]
