# Generated by Django 2.0.6 on 2018-09-23 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0022_auto_20180923_1136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cargo',
            name='invoice_number',
        ),
        migrations.RemoveField(
            model_name='cargo',
            name='shipment',
        ),
        migrations.AddField(
            model_name='cargo',
            name='factura',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='from_factura', to='rest.Factura'),
        ),
    ]
