# Generated by Django 2.0.6 on 2018-09-30 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0023_auto_20180923_1207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='railbill',
            name='name',
        ),
        migrations.AddField(
            model_name='railbill',
            name='destination',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='rwb_destination_station', to='rest.Place'),
        ),
        migrations.AddField(
            model_name='railbill',
            name='dispatch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='rwb_dispatch_station', to='rest.Place'),
        ),
        migrations.AddField(
            model_name='railbill',
            name='number',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
