# Generated by Django 2.0.6 on 2018-10-16 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0027_auto_20181007_1210'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipment',
            name='buyer',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='facturas',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='invoices',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='rw_bill',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='seller',
        ),
        migrations.AddField(
            model_name='factura',
            name='shipment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rest.Shipment'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='shipment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rest.Shipment'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='name',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rest.Order'),
        ),
    ]
