# Generated by Django 2.0.6 on 2018-10-21 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0028_auto_20181016_1625'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='shipments',
        ),
        migrations.RemoveField(
            model_name='rtmefilemodel',
            name='content',
        ),
    ]
