# Generated by Django 2.0.6 on 2018-10-25 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0029_auto_20181021_0850'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargo',
            name='is_indexed',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='person',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='country', to='rest.Country'),
        ),
    ]
