# Generated by Django 2.0.6 on 2018-10-27 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0033_auto_20181027_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='grand_total',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
