# Generated by Django 2.0.6 on 2018-10-29 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0034_factura_grand_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='extra_cost',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='invoice',
            name='grand_total',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='invoice',
            name='total',
            field=models.FloatField(default=0.0),
        ),
    ]
