# Generated by Django 2.0.6 on 2018-10-31 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0035_auto_20181029_1847'),
    ]

    operations = [
        migrations.AddField(
            model_name='railbill',
            name='shipment',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rest.Shipment'),
        ),
    ]
