# Generated by Django 2.0.6 on 2018-11-04 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0037_auto_20181104_2010'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoadSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('road', models.CharField(blank=True, max_length=6, null=True)),
                ('in_station', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='road_in_station', to='rest.Place')),
                ('out_station', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='road_out_station', to='rest.Place')),
            ],
            options={
                'verbose_name': 'RoadSection',
                'verbose_name_plural': 'RoadSections',
            },
        ),
    ]
