# Generated by Django 2.0.6 on 2018-11-04 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0038_roadsection'),
    ]

    operations = [
        migrations.AddField(
            model_name='railbill',
            name='road_sections',
            field=models.ManyToManyField(related_name='rwb_road_sections', to='rest.RoadSection'),
        ),
        migrations.AlterField(
            model_name='railbill',
            name='destination',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rwb_destination_station', to='rest.Place'),
        ),
        migrations.AlterField(
            model_name='railbill',
            name='dispatch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rwb_dispatch_station', to='rest.Place'),
        ),
    ]
