# Generated by Django 2.0.6 on 2019-06-02 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0043_auto_20190602_1858'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kpsstation',
            old_name='kps_id',
            new_name='kpsId',
        ),
    ]
