# Generated by Django 2.0.6 on 2019-06-02 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0044_auto_20190602_1903'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kpsstation',
            name='kpsId',
        ),
    ]
