# Generated by Django 2.0.6 on 2019-06-02 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0045_remove_kpsstation_kpsid'),
    ]

    operations = [
        migrations.AddField(
            model_name='kpsstation',
            name='kpsId',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
